
export const CART_REMOVE_ITEM ='CART_REMOVE_ITEM';
export const CART_SAVE_SHIIPING_ADDRESS = 'CART_SAVE_SHIIPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_EMTY = 'CART_EMTY';


export const CART_ADD_REQUEST ='CART_ADD_REQUEST';
export const CART_ADD_SUCCESS='CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';


